FROM python:3.8-slim

WORKDIR /app

COPY . /app

RUN pip install --trusted-host pypi.python.org Flask

EXPOSE 6578

ENV FLASK_APP app.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=6578"]